import type { PracticeQuestionSeed } from '../types'

export const logarithmsTests: PracticeQuestionSeed[] = [
  {
    type: 'numeric',
    difficulty: 'easy',
    order: 1,
    points: 1,
    timeLimit: 0,
    tags: ['логарифмы', 'вычисление'],
    questionTitle: 'Вычисление логарифма (1)',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\log_{3} 162 - \\log_{3} 2',
    correctNumericAnswer: '4',
    hintText:
      'Сначала воспользуйтесь свойством логарифма разности: \\log_a b - \\log_a c = \\log_a \\frac{b}{c}.',
    hintFormula: '\\log_{3} 162 - \\log_{3} 2 = \\log_{3} \\frac{162}{2}',
    explanationText:
      'Применяем свойство логарифма разности, затем упрощаем 162 / 2 = 81 и вспоминаем, что 81 = 3^4.',
    explanationFormulas: [
      '\\log_{3} 162 - \\log_{3} 2 = \\log_{3} \\frac{162}{2}',
      '\\log_{3} \\frac{162}{2} = \\log_{3} 81',
      '\\log_{3} 81 = \\log_{3} 3^4 = 4',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'easy',
    order: 2,
    points: 1,
    timeLimit: 0,
    tags: ['логарифмы', 'вычисление'],
    questionTitle: 'Вычисление логарифма (2)',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\log_{2} 6{,}4 + \\log_{2} 10',
    correctNumericAnswer: '6',
    hintText: 'Используйте свойство логарифма произведения: \\log_a b + \\log_a c = \\log_a (bc).',
    hintFormula: '\\log_{2} 6{,}4 + \\log_{2} 10 = \\log_{2} (6{,}4 \\cdot 10)',
    explanationText:
      'Сначала объединяем логарифмы в один, затем замечаем, что 6,4 · 10 = 64 = 2^6.',
    explanationFormulas: [
      '\\log_{2} 6{,}4 + \\log_{2} 10 = \\log_{2} (6{,}4 \\cdot 10)',
      '\\log_{2} (6{,}4 \\cdot 10) = \\log_{2} 64',
      '\\log_{2} 64 = \\log_{2} 2^6 = 6',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'medium',
    order: 3,
    points: 2,
    timeLimit: 0,
    tags: ['логарифмы', 'свойства'],
    questionTitle: 'Логарифм с коренным основанием',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '6 \\log_{\\sqrt{13}} 13',
    correctNumericAnswer: '12',
    hintText: 'Используйте переход к новому основанию или вспомните, что \\sqrt{13} = 13^{1/2}.',
    hintFormula: '\\log_{\\sqrt{13}} 13 = \\log_{13^{1/2}} 13',
    explanationText:
      'Представляем корень через степень и применяем формулу перехода: \\log_{a^k} b = \\frac{1}{k} \\log_a b.',
    explanationFormulas: [
      '\\log_{\\sqrt{13}} 13 = \\log_{13^{1/2}} 13',
      '\\log_{13^{1/2}} 13 = \\frac{1}{1/2} \\log_{13} 13 = 2',
      '6 \\log_{\\sqrt{13}} 13 = 6 \\cdot 2 = 12',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'medium',
    order: 4,
    points: 2,
    timeLimit: 0,
    tags: ['логарифмы', 'вычисление'],
    questionTitle: 'Вычисление логарифма (3)',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\log_{2} 6{,}4 + \\log_{2} 5',
    correctNumericAnswer: '5',
    hintText: 'Снова используйте свойство произведения: \\log_a b + \\log_a c = \\log_a (bc).',
    hintFormula: '\\log_{2} 6{,}4 + \\log_{2} 5 = \\log_{2} (6{,}4 \\cdot 5)',
    explanationText:
      'Переносим сумму под один логарифм, затем упрощаем произведение и выражаем через степень двойки.',
    explanationFormulas: [
      '\\log_{2} 6{,}4 + \\log_{2} 5 = \\log_{2} (6{,}4 \\cdot 5)',
      '\\log_{2} (6{,}4 \\cdot 5) = \\log_{2} 32',
      '\\log_{2} 32 = \\log_{2} 2^5 = 5',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'hard',
    order: 5,
    points: 3,
    timeLimit: 0,
    tags: ['логарифмы', 'свойства'],
    questionTitle: 'Логарифм с основанием меньше 1',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\log_{0{,}7} 10 - \\log_{0{,}7} 7',
    correctNumericAnswer: '-1',
    hintText: 'Используйте свойство разности логарифмов и вспомните связь с обратным числом.',
    hintFormula: '\\log_{0{,}7} 10 - \\log_{0{,}7} 7 = \\log_{0{,}7} \\frac{10}{7}',
    explanationText:
      'Сначала объединяем логарифмы, затем представляем дробь как степень основания 0{,}7 в отрицательной степени.',
    explanationFormulas: [
      '\\log_{0{,}7} 10 - \\log_{0{,}7} 7 = \\log_{0{,}7} \\frac{10}{7}',
      '\\frac{10}{7} = \\left(\\frac{7}{10}\\right)^{-1} = (0{,}7)^{-1}',
      '\\log_{0{,}7} (0{,}7)^{-1} = -1',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'hard',
    order: 6,
    points: 3,
    timeLimit: 0,
    tags: ['логарифмы', 'степени'],
    questionTitle: 'Логарифм корня',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '6 \\log_{7} \\sqrt[6]{7}',
    correctNumericAnswer: '1',
    hintText: 'Запишите корень через степень и воспользуйтесь свойством логарифма степени.',
    hintFormula: '\\sqrt[6]{7} = 7^{1/6}',
    explanationText:
      'Представляем корень как степень, выносим показатель перед логарифмом и упрощаем.',
    explanationFormulas: [
      '\\sqrt[6]{7} = 7^{1/6}',
      '\\log_{7} \\sqrt[6]{7} = \\log_{7} 7^{1/6} = \\frac{1}{6} \\log_{7} 7 = \\frac{1}{6}',
      '6 \\cdot \\frac{1}{6} = 1',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'hard',
    order: 7,
    points: 3,
    timeLimit: 0,
    tags: ['логарифмы', 'вычисление'],
    questionTitle: 'Логарифм с основанием меньше 1 (2)',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\log_{0{,}6} 50 - \\log_{0{,}6} 18',
    correctNumericAnswer: '-2',
    hintText:
      'Используйте свойство разности логарифмов и попробуйте упростить дробь \\frac{50}{18}.',
    hintFormula: '\\log_{0{,}6} 50 - \\log_{0{,}6} 18 = \\log_{0{,}6} \\frac{50}{18}',
    explanationText:
      'Сначала объединяем логарифмы, затем представляем результат как степень основания 0{,}6 (или эквивалентного 3/5).',
    explanationFormulas: [
      '\\log_{0{,}6} 50 - \\log_{0{,}6} 18 = \\log_{0{,}6} \\frac{50}{18}',
      '\\frac{50}{18} = \\frac{25}{9}',
      '\\frac{25}{9} = \\left(\\frac{3}{5}\\right)^{-2}',
      '\\log_{3/5} (3/5)^{-2} = -2',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'hard',
    order: 8,
    points: 3,
    timeLimit: 0,
    tags: ['логарифмы', 'новое основание'],
    questionTitle: 'Переход к новому основанию',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\frac{\\log_{9} 28}{\\log_{9} 7} + \\log_{7} \\frac{7}{4}',
    correctNumericAnswer: '2',
    hintText:
      'Сначала упростите дробь с логарифмами через переход к основанию 7, затем используйте свойство логарифма произведения.',
    hintFormula: '\\frac{\\log_{9} 28}{\\log_{9} 7} = \\log_{7} 28',
    explanationText:
      'Используем формулу перехода к новому основанию, а затем сворачиваем сумму логарифмов в один логарифм произведения.',
    explanationFormulas: [
      '\\frac{\\log_{9} 28}{\\log_{9} 7} = \\log_{7} 28',
      '\\log_{7} 28 + \\log_{7} \\frac{7}{4} = \\log_{7} \\left(28 \\cdot \\frac{7}{4}\\right)',
      '28 \\cdot \\frac{7}{4} = 49',
      '\\log_{7} 49 = \\log_{7} 7^2 = 2',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'medium',
    order: 9,
    points: 2,
    timeLimit: 0,
    tags: ['логарифмы', 'вычисление'],
    questionTitle: 'Вычисление логарифма (4)',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '\\log_{2} 96 - \\log_{2} 3',
    correctNumericAnswer: '5',
    hintText: 'Снова воспользуйтесь свойством: \\log_a b - \\log_a c = \\log_a \\frac{b}{c}.',
    hintFormula: '\\log_{2} 96 - \\log_{2} 3 = \\log_{2} \\frac{96}{3}',
    explanationText:
      'Объединяем разность в один логарифм и выражаем результат через степень двойки.',
    explanationFormulas: [
      '\\log_{2} 96 - \\log_{2} 3 = \\log_{2} \\frac{96}{3}',
      '\\frac{96}{3} = 32',
      '\\log_{2} 32 = \\log_{2} 2^5 = 5',
    ],
  },
  {
    type: 'numeric',
    difficulty: 'medium',
    order: 10,
    points: 2,
    timeLimit: 0,
    tags: ['логарифмы', 'степени'],
    questionTitle: 'Логарифм корня (2)',
    questionText: 'Вычислите значение выражения:',
    questionFormula: '8 \\log_{5} \\sqrt[8]{5}',
    correctNumericAnswer: '1',
    hintText: 'Запишите корень через степень и примените свойство: \\log_a (a^k) = k.',
    hintFormula: '\\sqrt[8]{5} = 5^{1/8}',
    explanationText:
      'Представляем корень как степень числа 5 и выносим показатель степени перед логарифмом.',
    explanationFormulas: [
      '\\sqrt[8]{5} = 5^{1/8}',
      '\\log_{5} \\sqrt[8]{5} = \\log_{5} 5^{1/8} = \\frac{1}{8} \\log_{5} 5 = \\frac{1}{8}',
      '8 \\cdot \\frac{1}{8} = 1',
    ],
  },
]
